version: 0.2

phases:
  install:
    commands:
      - echo pre_build step...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      - echo Entered the build phase...
      - echo Building the Docker image...
      - ls
      - docker build -t $DOCKER_USERNAME/fyle_qbo-app-2 .
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Pushing the Docker image...
      - ls
      - docker push $DOCKERHUB_USERNAME/fyle_qbo-app-2
