# This is used to run the app locally
version: '3.7'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: npm run local_dev_dc
    restart: unless-stopped
    working_dir: /app
    volumes: 
    - ./:/app
    - node_modules:/app/node_modules
    ports:
    - 4200:4200
    environment: 
      production: "False"
      FYLE_CLIENT_ID: tpaYfU7VLyrEN
      API_URL: http://localhost:8002/api
      APP_URL: http://localhost:4200
      OLD_QBO_APP_URL: http://localhost:4201/auth/shared_login
      CALLBACK_URI: http://localhost:4200/auth/callback
      QBO_CLIENT_ID: ABTemcw1ngLRye1iqW25EI2CyNUzdBSkNYWYxaFtkaJNgRcbM5
      QBO_SCOPE: com.intuit.quickbooks.accounting
      QBO_AUTHORIZE_URI: https://appcenter.intuit.com/connect/oauth2
      QBO_APP_URL: https://app.sandbox.qbo.intuit.com
      SENTRY_DSN: ''
      SENTRY_ENV: ''
      RELEASE: 'local'
      FYLE_APP_URL: https://app.fyle.tech
      E2E_TESTS_ENV: Local
      TESTS_WORKSPACEID: 1
      REFINER_ONBOARDING_DONE_SURVEY_ID: 
      REFINER_EXPORT_DONE_SURVEY_ID: 
      E2E_TESTS_WORKSPACE_ID: 
      E2E_TESTS_CLIENT_ID: 

volumes:
  node_modules: