# NOTE - Dont rename this to 'Dockerfile'

# base image
FROM node:14.18-alpine as build

# Create a working directory for app and node_modules
RUN mkdir /app
RUN mkdir /app/node_modules

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install

# add app
COPY . /app

# expose port 4200
EXPOSE 4200
