# This is used to run the app locally
version: '3.7'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ng serve --configuration=docker --host 0.0.0.0 --disable-host-check
    restart: unless-stopped
    volumes: 
    - ./:/app
    ports:
    - 4200:4200
    environment: 
      production: "False"
      FYLE_URL: 
      FYLE_CLIENT_ID: 'FYLE_CLIENT_ID'
      API_URL: 
      APP_URL: 
      CALLBACK_URI: 
      QBO_CLIENT_ID: 
      QBO_SCOPE: com.intuit.quickbooks.accounting
      QBO_AUTHORIZE_URL: https://appcenter.intuit.com/connect/oauth2
      QBO_APP_URL: 
      SENTRY_DSN: ''
      RELEASE: 'local'
