apiVersion: v1
kind: Service
metadata:
  name: qbo-app-2
  namespace: integrations
  labels:
    app: qbo-app-2
spec:
  ports:
    - port: 80
  selector:
    app: qbo-app-2
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbo-app-2
  namespace: integrations
  labels:
    app: qbo-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbo-app-2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qbo-app-2
    spec:
      containers:
        - name: qbo-app-2
          image: docker.io/${DOCKERHUB_USERNAME}/fyle_qbo-app-2:${RELEASE_VERSION}
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 200Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: qbo-app-2-secrets
      imagePullSecrets:
        - name: myregistrykey2
