name: Build and Deploy Documentation to Github Page

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy-documentation:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.20
      - name: Install dependency
        run: npm install -g @compodoc/compodoc
      - name: Generate docs
        run: compodoc -p tsconfig.doc.json
      - name: Deploy to github page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation
