name: End to End Tests on PR Approval - Staging

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [labeled]

jobs:
  end-to-end-test:
    if: (github.event_name == 'pull_request_review' && github.event.review.state == 'approved') || (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'run e2e tests')
    runs-on: macos-latest
    environment: End to End Test - Staging
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'always'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.18
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
              - 'cypress/**'
      - name: Install dependencies
        if: steps.filter.outputs.src == 'true'
        run: npm install --prefix cypress
      - name: Prepare for end to end tests
        if: steps.filter.outputs.src == 'true'
        run: npm run setup_e2e_test
      - name: Cypress run
        if: steps.filter.outputs.src == 'true'
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: chrome
          tag: ${{ secrets.E2E_TESTS_ENV }}
      - name: End to End Test Coverage
        uses: fylein/comment-test-coverage@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: cypress/coverage/coverage-summary.json
          title: End to End Test Coverage
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
      COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
      APP_URL: ${{ secrets.APP_URL }}
      API_URL: ${{ secrets.API_URL }}
      E2E_TESTS_ENV: ${{ secrets.E2E_TESTS_ENV }}
      E2E_TESTS_WORKSPACE_ID: ${{ secrets.E2E_TESTS_WORKSPACE_ID }}
      E2E_TESTS_CLIENT_ID: ${{ secrets.E2E_TESTS_CLIENT_ID }}
      E2E_TESTS_REFRESH_TOKEN: ${{ secrets.E2E_TESTS_REFRESH_TOKEN }}
      E2E_TESTS_ORG_ID: ${{ secrets.E2E_TESTS_ORG_ID }}
