name: End to End Tests - Cypress

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.18
      - name: Install dependencies
        run: npm install
      - name: Prepare for end to end tests
        run: npm run setup_e2e_test
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
        env:
          API_URL: ${{secrets.API_URL}} 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
