name: End to End Tests on PR Approval - Staging

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  end-to-end-test:
    if: github.event.review.state == 'approved'
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.18
      - name: Install dependencies
        run: npm install --prefix cypress
      - name: Prepare for end to end tests
        run: npm run setup_e2e_test
      - name: Cypress run
      continue-on-error: true
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: chrome
          tag: ${{ secrets.E2E_TESTS_ENV }}
      - name: 'Upload screenshots and videos to Slack'
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        if: failure()
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channels: 'integration_test_runs'
          message-text: ':pepe-dance: End to End tests (on staging) just got completed. I have placed the screenshots and videos in this thread :pepe-dance:'
      - name: End to End Test Coverage
        uses: fylein/comment-test-coverage@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: cypress/coverage/coverage-summary.json
          title: End to End Test Coverage
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      E2E_TESTS_ENV: ${{ secrets.E2E_TESTS_ENV }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FYLE_CLIENT_ID: ${{ secrets.FYLE_CLIENT_ID }}
      CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
      API_URL: ${{ secrets.API_URL }}
      APP_URL: ${{ secrets.APP_URL }}
      QBO_CLIENT_ID: ${{ secrets.QBO_CLIENT_ID }}
      QBO_SCOPE: ${{ secrets.QBO_SCOPE }}
      QBO_AUTHORIZE_URI: ${{ secrets.QBO_AUTHORIZE_URI }}
      QBO_APP_URL: ${{ secrets.QBO_APP_URL }}
      FYLE_APP_URL: ${{ secrets.FYLE_APP_URL }}
      E2E_TESTS_WORKSPACE_ID: ${{ secrets.E2E_TESTS_WORKSPACE_ID }}
      E2E_TESTS_CLIENT_ID: ${{ secrets.E2E_TESTS_CLIENT_ID }}
      E2E_TESTS_REFRESH_TOKEN: ${{ secrets.E2E_TESTS_REFRESH_TOKEN }}
      COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
      COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
