name: Lint and Tests

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: TypeScript Lint GitHub Action
      uses: actions/setup-node@v1
      with:
        node-version: 14.18
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint