name: Manually Trigger End to End Tests - With environment

on:
  workflow_dispatch:
    inputs:
      env-name:
        type: choice
        required: true
        description: Environment
        options: 
        - End to End Test - Staging
        - End to End Test - Production

jobs:
  approved:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.env-name }}
    steps:
      - run: echo "Running e2eeeee test on ${{ github.event.inputs.env-name }}!"
