on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: Environment
        options: 
        - staging
        - production

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved, running e2eeeee test!"
